##
## Dependabot. Only check for major updates and security issues, as this repository needs careful checking
## before any updates. Major changes usually introduce useful functionality, and so this could be allowed
## as a change.
##

version: 2
updates:

# Check for changes to GitHub actions on a monthly basis. This should keep the repo
# updated, without being too annoying
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

# Ignore updates to Python pip dependencies. This will turn off all except security
# alerts
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
